export const EXITO: number = 0;
export const ERROR_GENERAL: number = -1;

export const mapErrorMessages: Map<number, string> = new Map([
    [-2, 'FALTAN_DATOS_DE_ENTRADA'],
    [1, 'PSICOLOGO_TIENE_IDENTIFICAR_INCORRECTO'],
    [2, 'ENCUESTA_EXISTENTE'],
    [3, 'ENCUESTA_NO_EXISTE'],
    [4, 'ENCUESTA_NO_SE_PUEDE_ELIMINAR_PORQUE_HA_INICIADO'],
    [5, 'PSICOLOGO_YA_CUENTA_CON_DICHA_ENCUESTA'],
    [6, 'PAGINA_SOLO_ENTRE_1_Y_3'],
    [7, 'PREGUNTA_TIENE_TIPO_INVALIDO'],
    [8, 'PREGUNTA_NO_EXISTE'],
    [9, 'PREGUNTA_NO_SE_PUEDE_MODIFICAR_PORQUE_ENCUESTA_HA_INICIADO'],
    [10, 'PREGUNTA_NO_SE_PUEDE_AGREGAR_PORQUE_ENCUESTA_HA_INICIADO'],
    [11, 'ALTERNATIVA_NO_SE_PUEDE_MODIFICAR_PORQUE_ENCUESTA_HA_INICIADO'],
    [12, 'ALTERNATIVA_NO_EXISTE'],
    [13, 'ENCUESTA_SOLO_PUEDE_SER_ELIMINADA_POR_PSICOLOGO_CREADOR'],
    [14, 'PSICOLOGO_NO_PUEDE_DUPLICAR_ENCUESTA'],
    [15, 'ENCUESTA_SOLO_PUEDE_SER_COMPARTIDA_POR_PSICOLOGO_CREADOR'],
    [16, 'PSICOLOGO_NO_PUEDE_CREAR_PREGUNTAS_EN_DICHA_ENCUESTA'],
    [17, 'PREGUNTA_EXISTENTE_EN_DICHA_ENCUESTA'],
    [18, 'ALTERNATIVA_NO_SE_PUEDE_REPETIR'],
    [19, 'PSICOLOGO_NO_PUEDE_mMODIFICAR_PREGUNTAS_EN_DICHA_ENCUESTA'],
    [51, 'CREDENCIALES_INCORRECTAS']
]);